# Generated by Django 4.0.3 on 2022-05-08 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('is_group', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='BOTH', max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('university', models.CharField(max_length=20)),
                ('show_gender', models.CharField(choices=[('MALE', 'Men'), ('FEMALE', 'Women'), ('BOTH', 'Both')], default='FEMALE', max_length=10)),
                ('location', models.CharField(default='', max_length=100)),
                ('citylat', models.DecimalField(decimal_places=6, default='-2.0180319', max_digits=9)),
                ('citylong', models.DecimalField(decimal_places=6, default='52.5525525', max_digits=9)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('is_group', models.BooleanField(default=True)),
                ('total_members', models.IntegerField(blank=True, default=1)),
                ('share_link', models.SlugField()),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
