/* CHATS */

export const LIST_CHATS_REQUEST = 'LIST_CHATS_REQUEST';
export const LIST_CHATS_SUCCESS = 'LIST_CHATS_SUCCESS';
export const LIST_CHATS_FAIL = 'LIST_CHATS_FAIL';

export const GET_CHAT_REQUEST = 'GET_CHAT_REQUEST';
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS';
export const GET_CHAT_FAIL = 'GET_CHAT_FAIL';

export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAIL = 'CREATE_CHAT_FAIL';
export const CREATE_CHAT_RESET = 'CREATE_CHAT_RESET';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAIL = 'DELETE_CHAT_FAIL';
export const DELETE_CHAT_RESET = 'DELETE_CHAT_RESET';

export const GET_RECEIVER_PROFILE_FAIL = 'GET_RECEIVER_PROFILE_FAIL';
export const GET_RECEIVER_PROFILE_REQUEST = 'GET_RECEIVER_PROFILE_REQUEST';
export const GET_RECEIVER_PROFILE_SUCCESS = 'GET_RECEIVER_PROFILE_SUCCESS';
