export const LIST_CONVERSATIONS_REQUEST = 'LIST_CONVERSATIONS_REQUEST';
export const LIST_CONVERSATIONS_SUCCESS = 'LIST_CONVERSATIONS_SUCCESS';
export const LIST_CONVERSATIONS_FAIL = 'LIST_CONVERSATIONS_FAIL';

export const LIST_CONVERSATION_MESSAGES_REQUEST =
  'LIST_CONVERSATION_MESSAGES_REQUEST';
export const LIST_CONVERSATION_MESSAGES_SUCCESS =
  'LIST_CONVERSATION_MESSAGES_SUCCESS';
export const LIST_CONVERSATION_MESSAGES_FAIL =
  'LIST_CONVERSATION_MESSAGES_FAIL';

export const CREATE_CONVERSATION_REQUEST = 'CREATE_CONVERSATION_REQUEST';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const CREATE_CONVERSATION_FAIL = 'CREATE_CONVERSATION_FAIL';
export const CREATE_CONVERSATION_RESET = 'CREATE_CONVERSATION_RESET';

export const DELETE_CONVERSATION_REQUEST = 'DELETE_CONVERSATION_REQUEST';
export const DELETE_CONVERSATION_SUCCESS = 'DELETE_CONVERSATION_SUCCESS';
export const DELETE_CONVERSATION_FAIL = 'DELETE_CONVERSATION_FAIL';
export const DELETE_CONVERSATION_RESET = 'DELETE_CONVERSATION_RESET';
