export const REPORT_PROFILE_REQUEST = 'REPORT_PROFILE_REQUEST';
export const REPORT_PROFILE_SUCCESS = 'REPORT_PROFILE_SUCCESS';
export const REPORT_PROFILE_FAIL = 'REPORT_PROFILE_FAIL';
export const REPORT_PROFILE_RESET = 'REPORT_PROFILE_RESET';
