export const LIST_SWIPE_REQUEST = 'LIST_SWIPE_REQUEST';
export const LIST_SWIPE_SUCCESS = 'LIST_SWIPE_SUCCESS';
export const LIST_SWIPE_FAIL = 'LIST_SWIPE_FAIL';

export const GET_CURRENT_SWIPE_PROFILE_REQUEST =
  'GET_CURRENT_SWIPE_PROFILE_REQUEST';

export const GET_CURRENT_SWIPE_PROFILE_SUCCESS =
  'GET_CURRENT_SWIPE_PROFILE_SUCCESS';

export const GET_CURRENT_SWIPE_PROFILE_FAIL = 'GET_CURRENT_SWIPE_PROFILE_FAIL';
