export const LIST_BLOCKED_PROFILES_REQUEST = 'LIST_BLOCKED_PROFILES_REQUEST';
export const LIST_BLOCKED_PROFILES_SUCCESS = 'LIST_BLOCKED_PROFILES_SUCCESS';
export const LIST_BLOCKED_PROFILES_FAIL = 'LIST_BLOCKED_PROFILES_FAIL';

export const BLOCK_PROFILE_REQUEST = 'BLOCK_PROFILE_REQUEST';
export const BLOCK_PROFILE_SUCCESS = 'BLOCK_PROFILE_SUCCESS';
export const BLOCK_PROFILE_FAIL = 'BLOCK_PROFILE_FAIL';
export const BLOCK_PROFILE_RESET = 'BLOCK_PROFILE_RESET';

export const DISBLOCK_PROFILE_REQUEST = 'DISBLOCK_PROFILE_REQUEST';
export const DISBLOCK_PROFILE_SUCCESS = 'DISBLOCK_PROFILE_SUCCESS';
export const DISBLOCK_PROFILE_FAIL = 'DISBLOCK_PROFILE_FAIL';
export const DISBLOCK_PROFILE_RESET = 'DISBLOCK_PROFILE_RESET';
