export const LIST_CONVERSATIONS_REQUEST = 'LIST_CONVERSATIONS_REQUEST';
export const LIST_CONVERSATIONS_SUCCESS = 'LIST_CONVERSATIONS_SUCCESS';
export const LIST_CONVERSATIONS_FAIL = 'LIST_CONVERSATIONS_FAIL';

export const LIST_CONVERSATION_MESSAGES_REQUEST =
  'LIST_CONVERSATION_MESSAGES_REQUEST';
export const LIST_CONVERSATION_MESSAGES_SUCCESS =
  'LIST_CONVERSATION_MESSAGES_SUCCESS';
export const LIST_CONVERSATION_MESSAGES_FAIL =
  'LIST_CONVERSATION_MESSAGES_FAIL';

export const START_CONVERSATION_REQUEST = 'START_CONVERSATION_REQUEST';
export const START_CONVERSATION_SUCCESS = 'START_CONVERSATION_SUCCESS';
export const START_CONVERSATION_FAIL = 'START_CONVERSATION_FAIL';
export const START_CONVERSATION_RESET = 'START_CONVERSATION_RESET';

export const DELETE_CONVERSATION_REQUEST = 'DELETE_CONVERSATION_REQUEST';
export const DELETE_CONVERSATION_SUCCESS = 'DELETE_CONVERSATION_SUCCESS';
export const DELETE_CONVERSATION_FAIL = 'DELETE_CONVERSATION_FAIL';
export const DELETE_CONVERSATION_RESET = 'DELETE_CONVERSATION_RESET';
export const ADD_CONVERSATION_MESSAGE = 'ADD_CONVERSATION_MESSAGE';
export const ADD_CONVERSATION_MESSAGES = 'ADD_CONVERSATION_MESSAGES';

export const LOAD_MORE_MESSAGES_REQUESTS = 'LOAD_MORE_MESSAGES_REQUESTS';
export const LOAD_MORE_MESSAGES_SUCCESS = 'LOAD_MORE_MESSAGES_SUCCESS';
export const LOAD_MORE_MESSAGES_FAIL = 'LOAD_MORE_MESSAGES_FAIL';
export const LOAD_MORE_MESSAGES_RESET = 'LOAD_MORE_MESSAGES_RESET';

export const LOAD_MORE_CONVERSATIONS_REQUESTS =
  'LOAD_MORE_CONVERSATIONS_REQUESTS';
export const LOAD_MORE_CONVERSATIONS_SUCCESS =
  'LOAD_MORE_CONVERSATIONS_SUCCESS';
export const LOAD_MORE_CONVERSATIONS_FAIL = 'LOAD_MORE_CONVERSATIONS_FAIL';

export const GET_GROUP_CHAT_REQUEST = 'GET_GROUP_CHAT_REQUEST';
export const GET_GROUP_CHAT_SUCCESS = 'GET_GROUP_CHAT_SUCCESS';
export const GET_GROUP_CHAT_FAIL = 'GET_GROUP_CHAT_FAIL';
export const GET_GROUP_CHAT_RESET = 'GET_GROUP_CHAT_RESET';

export const LIST_GROUP_MESSAGES_REQUEST = 'LIST_GROUP_MESSAGES_REQUEST';
export const LIST_GROUP_MESSAGES_SUCCESS = 'LIST_GROUP_MESSAGES_SUCCESS';
export const LIST_GROUP_MESSAGES_FAIL = 'LIST_GROUP_MESSAGES_FAIL';
export const LIST_GROUP_MESSAGES_RESET = 'LIST_GROUP_MESSAGES_RESET';
