export const LIST_GROUP_REQUEST = 'GROUP_LIST_REQUEST';
export const LIST_GROUP_SUCCESS = 'GROUP_LIST_SUCCESS';
export const LIST_GROUP_FAIL = 'GROUP_LIST_FAIL';
export const LIST_GROUP_RESET = 'GROUP_LIST_RESET';

export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAIL = 'GET_GROUP_FAIL';
export const GET_GROUP_RESET = 'GET_GROUP_RESET';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';
export const CREATE_GROUP_RESET = 'CREATE_GROUP_RESET';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL';
export const DELETE_GROUP_RESET = 'DELETE_GROUP_RESET';

export const JOIN_GROUP_REQUEST = 'JOIN_GROUP_REQUEST';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const JOIN_GROUP_FAIL = 'JOIN_GROUP_FAIL';
export const JOIN_GROUP_RESET = 'JOIN_GROUP_RESET';

export const LEAVE_GROUP_REQUEST = 'LEAVE_GROUP_REQUEST';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_FAIL = 'LEAVE_GROUP_FAIL';
export const LEAVE_GROUP_RESET = 'LEAVE_GROUP_RESET';

export const REMOVE_MEMBER_REQUEST = 'REMOVE_MEMBER_REQUEST';
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS';
export const REMOVE_MEMBER_FAIL = 'REMOVE_MEMBER_FAIL';
export const REMOVE_MEMBER_RESET = 'REMOVE_MEMBER_RESET';
