export const LIST_SWIPE_REQUEST = 'LIST_SWIPE_REQUEST';
export const LIST_SWIPE_SUCCESS = 'LIST_SWIPE_SUCCESS';
export const LIST_SWIPE_FAIL = 'LIST_SWIPE_FAIL';

export const GET_SWIPE_PROFILE_REQUEST = 'GET_SWIPE_PROFILE_REQUEST';
export const GET_SWIPE_PROFILE_SUCCESS = 'GET_SWIPE_PROFILE_SUCCESS';
export const GET_SWIPE_PROFILE_FAIL = 'GET_SWIPE_PROFILE_FAIL';
export const GET_SWIPE_PROFILE_RESET = 'GET_SWIPE_PROFILE_RESET';

export const LIST_LIKES_REQUEST = 'LIST_LIKES_REQUEST';
export const LIST_LIKES_SUCCESS = 'LIST_LIKES_SUCCESS';
export const LIST_LIKES_FAIL = 'LIST_LIKES_FAIL';

export const LIKE_PROFILE_REQUEST = 'LIKE_PROFILE_REQUEST';
export const LIKE_PROFILE_SUCCESS = 'LIKE_PROFILE_SUCCESS';
export const LIKE_PROFILE_FAIL = 'LIKE_PROFILE_FAIL';
export const LIKE_PROFILE_RESET = 'LIKE_PROFILE_RESET';

export const REMOVE_LIKE_REQUEST = 'REMOVE_LIKE_REQUEST';
export const REMOVE_LIKE_SUCCESS = 'REMOVE_LIKE_SUCCESS';
export const REMOVE_LIKE_FAIL = 'REMOVE_LIKE_FAIL';
export const REMOVE_LIKE_RESET = 'REMOVE_LIKE_RESET';

export const LIST_MATCH_REQUEST = 'LIST_MATCH_REQUEST';
export const LIST_MATCH_SUCCESS = 'LIST_MATCH_SUCCESS';
export const LIST_MATCH_FAIL = 'LIST_MATCH_FAIL';

export const DELETE_MATCH_REQUEST = 'DELETE_MATCH_REQUEST';
export const DELETE_MATCH_SUCCESS = 'DELETE_MATCH_SUCCESS';
export const DELETE_MATCH_FAIL = 'DELETE_MATCH_FAIL';
export const DELETE_MATCH_RESET = 'DELETE_MATCH_RESET';

export const LOAD_MORE_MATCH_REQUEST = 'LOAD_MORE_MATCH_REQUEST';
export const LOAD_MORE_MATCH_SUCCESS = 'LOAD_MORE_MATCH_SUCCESS';
export const LOAD_MORE_MATCH_FAIL = 'LOAD_MORE_MATCH_FAIL';
