export const AUTHENTICATE = 'AUTHENTICATE';

export const USER_LOCATION_REQUEST = 'USER_LOCATION_REQUEST';
export const USER_LOCATION_SUCCESS = 'USER_LOCATION_SUCCESS';
export const USER_LOCATION_FAIL = 'USER_LOCATION_FAIL';

export const USER_GET_PROFILE_REQUEST = 'USER_GET_PROFILE_REQUEST';
export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS';
export const USER_GET_PROFILE_FAIL = 'USER_GET_PROFILE_FAIL';
export const USER_GET_PROFILE_RESET = 'USER_GET_PROFILE_RESET';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';
export const USER_CREATE_RESET = 'USER_CREATE_RESET';

export const USER_ADD_PHOTO_REQUEST = 'USER_ADD_PHOTO_REQUEST';
export const USER_ADD_PHOTO_SUCCESS = 'USER_ADD_PHOTO_SUCCESS';
export const USER_ADD_PHOTO_FAIL = 'USER_ADD_PHOTO_FAIL';
export const USER_ADD_PHOTO_RESET = 'USER_ADD_PHOTO_RESET';

export const USER_UPDATE_PHOTO_REQUEST = 'USER_UPDATE_PHOTO_REQUEST';
export const USER_UPDATE_PHOTO_SUCCESS = 'USER_UPDATE_PHOTO_SUCCESS';
export const USER_UPDATE_PHOTO_FAIL = 'USER_UPDATE_PHOTO_FAIL';
export const USER_UPDATE_PHOTO_RESET = 'USER_UPDATE_PHOTO_RESET';

export const USER_REMOVE_PHOTO_REQUEST = 'USER_REMOVE_PHOTO_REQUEST';
export const USER_REMOVE_PHOTO_SUCCESS = 'USER_REMOVE_PHOTO_SUCCESS';
export const USER_REMOVE_PHOTO_FAIL = 'USER_REMOVE_PHOTO_FAIL';
export const USER_REMOVE_PHOTO_RESET = 'USER_REMOVE_PHOTO_RESET';

export const USER_LIST_PHOTOS_REQUEST = 'USER_LIST_PHOTOS_REQUEST';
export const USER_LIST_PHOTOS_SUCCESS = 'USER_LIST_PHOTOS_SUCCESS';
export const USER_LIST_PHOTOS_FAIL = 'USER_LIST_PHOTOS_FAIL';
export const USER_LIST_PHOTOS_RESET = 'USER_LIST_PHOTOS_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const REPORT_PROFILE_REQUEST = 'REPORT_PROFILE_REQUEST';
export const REPORT_PROFILE_SUCCESS = 'REPORT_PROFILE_SUCCESS';
export const REPORT_PROFILE_FAIL = 'REPORT_PROFILE_FAIL';
export const REPORT_PROFILE_RESET = 'REPORT_PROFILE_RESET';

export const RECOVER_CODE_REQUEST = 'RECOVER_CODE_REQUEST';
export const RECOVERY_CODE_SUCCESS = 'RECOVERY_CODE_SUCCESS';
export const RECOVERY_CODE_FAIL = 'RECOVERY_CODE_FAIL';
export const RECOVERY_CODE_RESET = 'RECOVERY_CODE_RESET';

export const VALIDATE_CODE_REQUEST = 'VALIDATE_CODE_REQUEST';
export const VALIDATE_CODE_SUCCESS = 'VALIDATE_CODE_SUCCESS';
export const VALIDATE_CODE_FAIL = 'VALIDATE_CODE_FAIL';
export const VALIDATE_CODE_RESET = 'VALIDATE_CODE_RESET';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET';
