# Generated by Django 4.0.3 on 2022-05-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_photo_profile_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photos',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
