name: Deployment

on:
  push: 
    branches: [deployment-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: npm
        
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build for IOS
        env:
          EAS_JSON: ${{ secrets.EAS_JSON_ROCKET }}
        run: eas build -p ios --profile rocket
