name: Deployment

on:
  push:
    branches: [rocket]
  pull_request:
    branches: [rocket]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: npm

      - name: Create eas.json
        run: |
          cat > eas.json << EOF
          {
            "cli": {
              "version": ">= 2.7.0"
            },
            "build": {
              "rocket": {
                "env": {
                  "MODE": "rocket",
                  "ROCKET_API_URL": "${{ secrets.ROCKET_API_URL }}"
                }
              }
            },
            "submit": {
              "rocket": {
                "ios": {
                  "ascAppId": "${{secrets.APPLE_APP_ID}}"
                }
              }
            }
          }
          EOF

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build on EAS
        run: eas build --platform all --profile rocket --non-interactive

      - name: IOS deployment
        run: eas submit -p ios --latest --profile rocket
